<div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="panel panel-default">
        <div class="panel-heading">Grupos de Usuários
            <a title="Ver Grupos de Usuários" href="<?php echo $this->basePath ?>admin/user-group/list-items" class="btn btn-info btn-xs pull-right"><?php echo $this->glyphicon('search') ?> Ver Grupos de Usuários</a>
            <?php if ($this->edit): ?>
                <a title="Excluir Grupo" data-confirmation data-placement="bottom" href="<?php echo $this->basePath ?>admin/user-group/delete-item/cod/<?php echo $this->edit ?>" class="btn btn-danger btn-xs pull-right margin-right-xs"><?php echo $this->glyphicon('remove-sign') ?> Excluir Grupo</a>
            <?php endif; ?>
        </div>
        <div class="panel-body">
            <?php echo $this->form()->openTag('fm-user-group', ['method' => 'post', 'action' => $this->basePath . 'admin/user-group/new-item', 'class' => 'form-horizontal', 'role' => 'form']) ?>
            <fieldset>
                <?php
                echo $this->entity->getField('cod')->getViewComponent()
                        ->render()
                ?>
                <?php
                echo $this->entity->getField('name')->getViewComponent()
                        ->addData('value', $this->entity->getField('name')->getViewComponent()->getValue())
                        ->addData('value-change')
                        ->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8')
                ?>
                <?php
                echo $this->entity->getField('status')->getViewComponent()
                        ->addData('value', $this->entity->getField('status')->getViewComponent()->getValue())
                        ->addData('value-change')
                        ->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8')
                ?>
                <?php
                echo $this->form()->submitSave()
                        ->formGroup('col-xs-12', '', 'col-xs-offset-3 col-xs-8')
                ?>
            </fieldset>
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>