<div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>Perfis</h4>
        </div>
        <?php echo $this->form->open() ?>
        <div class="panel-body">
            <fieldset>
                <?php echo $this->form->cod->render() ?>
                <div class="form-group">
                    <?php echo $this->form->name->label('col-xs-3 text-right') ?>
                    <div class="col-xs-8">
                        <?php echo $this->form->name->render() ?>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->form->status->label('col-xs-3 text-right') ?>
                    <div class="col-xs-8">
                        <?php echo $this->form->status->render() ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-8 col-xs-offset-3">
                        <?php echo $this->form->submit->render() ?>
                    </div>
                </div>
            </fieldset>
        </div>
        <?php echo $this->form->close() ?>
    </div>
</div>