<?php if ($this->userLogged): ?>
    <?php
    $session = new \KF\Lib\System\Session('system');
    ?>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath ?>">KF</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="<?php echo $this->topItemAtual == 'painel' ? 'active' : '' ?> dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administração <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/admin/index/index"><span class="glyphicon glyphicon-th"></span> Painel Administrativo</a></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation" class="dropdown-header">Usuários</li>
                            <li><a href="/admin/user/new-item"><span class="glyphicon glyphicon-plus-sign"></span> Novo Usuário</a></li>
                            <li><a href="/admin/user/list-items"><span class="glyphicon glyphicon-list-alt"></span> Relatório de Usuários</a></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation" class="dropdown-header">Perfis</li>
                            <li><a href="/admin/user-group/new-item"><span class="glyphicon glyphicon-plus-sign"></span> Novo Perfil</a></li>
                            <li><a href="/admin/user-group/list-items"><span class="glyphicon glyphicon-list-alt"></span> Relatório de Perfis</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $session->identity['email'] ?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/admin/user/profile">Ver Perfil</a></li>
                            <li role="presentation" class="divider"></li>
                            <li><a href="/admin/auth/logout">Sair</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>