<?php if ($this->userLogged): ?>
    <?php
    $session = new \KF\Lib\System\Session('system');
    ?>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath ?>">KF</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="<?php echo $this->topItemAtual == 'painel' ? 'active' : '' ?> dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administração <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/admin/index/index"><?php echo $this->glyphicon('th') ?> Painel Administrativo</a></li>
                            <li role="presentation" class="divider"></li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Grupos de Usuários <b class="caret caret-right"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/admin/user-group/new-item"><?php echo $this->glyphicon('plus-sign') ?> Novo Grupo de Usuários</a></li>
                                    <li><a href="/admin/user-group/list-items"><?php echo $this->glyphicon('list-alt') ?> Ver Grupos de Usuários</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuários <b class="caret caret-right"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/admin/user/new-item"><?php echo $this->glyphicon('plus-sign') ?> Novo Usuário</a></li>
                                    <li><a href="/admin/user/list-items"><?php echo $this->glyphicon('list-alt') ?> Ver Usuários</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menus <b class="caret caret-right"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/admin/menu/list-items"><?php echo $this->glyphicon('list-alt') ?> Ver Menus</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $session->identity['email'] ?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/admin/user/profile">Ver Perfil</a></li>
                            <li role="presentation" class="divider"></li>
                            <li><a href="/admin/auth/logout">Sair</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>