<?php if ($this->userLogged): ?>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath ?>">KF</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="<?php echo $this->topItemAtual == 'painel' ? 'active' : '' ?> dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Painel <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/main/index"><span class="glyphicon glyphicon-th"></span> Painel Administrativo</a></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation" class="dropdown-header">Categorias</li>
                            <li><a href="/categorias/nova-categoria"><span class="glyphicon glyphicon-plus-sign"></span> Nova Categoria</a></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation" class="dropdown-header">Perguntas</li>
                            <li><a href="/perguntas/nova-pergunta"><span class="glyphicon glyphicon-plus-sign"></span> Nova Pergunta</a></li>
                        </ul>
                    </li>
                    <li class="<?php echo $this->topItemAtual == 'relatorios' ? 'active' : '' ?> dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li role="presentation" class="dropdown-header">Perguntas</li>
                            <li><a href="/perguntas/todas-perguntas"><span class="glyphicon glyphicon-list-alt"></span> Relatório de Perguntas</a></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation" class="dropdown-header">Categorias</li>
                            <li><a href="/categorias/todas-categorias"><span class="glyphicon glyphicon-list-alt"></span> Relatório de Categorias</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Perfil <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/admin/auth/perfil">Ver Perfil</a></li>
                            <li role="presentation" class="divider"></li>
                            <li><a href="/admin/auth/logout">Sair</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>