<div class="panel panel-default">
    <div class="panel-heading">Nova Categoria</div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" action="/categorias/salvar-categoria" method="post">

            <div class="form-group">
                <label class="control-label col-sm-2" for="pai">Pai</label>
                <div class="col-sm-4">
                    <?php echo $this->categorias('pai', null, false, true) ?>
                    <!--select name="pai" class="form-control" required>
                        <option value="0">Nenhum</option>
                        <?php foreach ($this->categorias as $categoria): ?>
                            <option value="" class="divider disabled" disabled></option>
                            <option value="<?php echo $categoria['cod'] ?>">&nbsp;<?php echo $categoria['nome'] ?></option>
                            <?php foreach ($categoria['filhos'] as $filho): ?>
                                <option value="" class="disabled" disabled>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $filho['nome'] ?></option>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </select-->
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2" for="nome">Nome</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="nome" placeholder="Nome da Categoria" required />
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </div>

        </form>
    </div>
</div>