<div class="row">
    <h2>Painel Administrativo</h2>
    <hr />
    <div class="col-sm-6">
        <div class="blockquote-box blockquote-warning clearfix">
            <div class="square pull-left">
                <span class="glyphicon glyphicon-tags glyphicon-lg"></span>
            </div>
            <h4>Categorias</h4>
            <p>
            <ul class="list-unstyled">
                <li><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;<a href="/categorias/todas-categorias">Relatório de Categorias</a></li>
                <li><span class="glyphicon glyphicon-plus-sign"></span>&nbsp;&nbsp;<a href="/categorias/nova-categoria">Nova Categoria</a></li>
            </ul>
            </p>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="blockquote-box blockquote-danger clearfix">
            <div class="square pull-left">
                <span class="glyphicon glyphicon-list glyphicon-lg"></span>
            </div>
            <h4>Perguntas</h4>
            <p>
            <ul class="list-unstyled">
                <li><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;<a href="/perguntas/todas-perguntas">Relatório de Perguntas</a></li>
                <li><span class="glyphicon glyphicon-plus-sign"></span>&nbsp;&nbsp;<a href="/perguntas/nova-pergunta">Nova Pergunta</a></li>
            </ul>
            </p>
        </div>
    </div>
</div>