<div class="col-sm-12">
    <div class="panel">
        <img class="pic img-circle" src="<?php echo $this->gravatar['thumbnailUrl'] ?>" alt="..." />
        <div class="name"><small><?php echo $this->usuario ?></small></div>
        <!--a href="#" class="btn btn-xs btn-primary pull-right" style="margin:10px;"><span class="glyphicon glyphicon-picture"></span> Change cover</a-->
    </div>
    <br />
    <hr />
</div>