<div class="panel panel-default">
    <div class="panel-heading">
        Mês: <strong class="lb-mes"><?php echo $this->folha['mes'] ?></strong> / Ano: <strong class="lb-ano"><?php echo $this->folha['ano'] ?></strong> &nbsp; <a href="#" id="btn-redefinir-datas" title="Editar data de início e término" class="label label-warning"><?php echo $this->glyphicon('calendar', 'glyphicons') ?> &nbsp;<?php echo "{$this->folha['inicio']} até {$this->folha['termino']}" ?></a>
        <div class="pull-right">
            <a href="<?php echo $this->basePath ?>main/index/ver-funcionarios-folha" id="btn-ver-mensal" type="button" title="Ver Funcionários dessa folha" class="btn btn-xs btn-info"><?php echo $this->glyphicon('nameplate', 'glyphicons') ?> Funcionários</a>
            <a href="<?php echo $this->basePath ?>main/index/ver-mensal" id="btn-ver-mensal" type="button" title="Ver Mensal" class="btn btn-xs btn-info"><?php echo $this->glyphicon('calendar', 'glyphicons') ?> Mensal</a>
            <!--button id="btn-redefinir-horarios" type="button" title="Redefinir horário desse mês" class="btn btn-xs btn-danger">Redefinir horários</button-->
        </div>
    </div>
    <div class="panel-body">
        <?php echo $this->form->open() ?>
        <?php echo $this->dg->getInputHidden() ?>
        <fieldset>
            <div class="form-group">
                <?php echo $this->form->dia->label('col-xs-3 text-right') ?>
                <div class="col-xs-7">
                    <div class="col-xs-4">
                        <?php echo $this->form->dia->render() ?>
                    </div>
                    <div class="col-xs-1 text-muted label label-<?php echo $this->fds ? 'info' : 'info' ?>" style="height: 36px; line-height: 30px;">
                        <ins><?php echo $this->domingoOuFeriado ? '100%' : '50%' ?></ins>
                    </div>
                </div>
            </div>
        </fieldset>
        <?php echo $this->form->close() ?>
    </div>
    <?php echo $this->dg->datagrid() ?>
</div>

<div class="modal fade" id="md-ponto" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form role="form" class="form-horizontal">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Editar Ponto de <strong class="lb-data margin-right-xs"></strong>(<?php echo $this->nomeDiaDaSemana ?>)<span class="pull-right margin-right-xs">Funcionário(a): <strong class="lb-funcionario"></strong></span></h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="cod" value="" />
                    <input type="hidden" name="feriado" value="<?php echo $this->fds ?>" />
                    <input type="hidden" name="sabado" value="<?php echo $this->sabado ?>" />
                    <input type="hidden" name="domingoOuFeriado" value="<?php echo $this->domingoOuFeriado ?>" />
                    <input type="hidden" name="folha" value="<?php echo $this->folha['cod'] ?>" />
                    <input type="hidden" name="total" value="<?php echo $this->horarioDefaults[6] ?>" />
                    <input type="hidden" name="total_extra" value="<?php echo $this->horarioDefaults[7] ?>" />
                    
                    <div class="form-group">
                        <label class="control-label col-xs-2" for='horario1'>Entrada 1</label>
                        <div class="col-xs-2">
                            <span data-name="horario1" data-tabindex="1" data-default-time="<?php echo $this->horarioDefaults[0] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>

                        <label class="control-label col-xs-2" for='horario3'>Entrada 2</label>
                        <div class="col-xs-2">
                            <span data-name="horario3" data-tabindex="3" data-default-time="<?php echo $this->horarioDefaults[2] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>

                        <label class="control-label col-xs-2" for='horario5'>Entrada 3</label>
                        <div class="col-xs-2">
                            <span data-name="horario5" data-tabindex="5" data-default-time="<?php echo $this->horarioDefaults[4] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-xs-2" for='horario2'>Saída 1</label>
                        <div class="col-xs-2">
                            <span data-name="horario2" data-tabindex="2" data-default-time="<?php echo $this->horarioDefaults[1] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>

                        <label class="control-label col-xs-2" for='horario4'>Saída 2</label>
                        <div class="col-xs-2">
                            <span data-name="horario4" data-tabindex="4" data-default-time="<?php echo $this->horarioDefaults[3] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>

                        <label class="control-label col-xs-2" for='horario6'>Saída 3</label>
                        <div class="col-xs-2">
                            <span data-name="horario6" data-tabindex="6" data-default-time="<?php echo $this->horarioDefaults[5] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>
                    </div>

                    <div class='form-group'>
                        <label class="control-label col-xs-3">Total Hs.</label>
                        <div class="col-xs-3">
                            <p class='form-control-static'><strong class="lb-total-hs">00:00</strong></p>
                        </div>

                        <label class="control-label col-xs-3">Total Hs. Extras</label>
                        <div class="col-xs-3">
                            <p class='form-control-static'><strong class="lb-total-hs-extras">00:00</strong></p>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary btn-save">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="md-redefinir-horarios" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form role="form" class="form-horizontal">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Redefinir horários do mês</h4>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label class="control-label col-xs-4">Mês: 4 / Ano: 2014</label>
                        <div class="col-xs-2">
                            <p class='form-control-static'>
                                <input type="hidden" name="cod" value="<?php echo $this->folha['cod'] ?>" />
                                <input type="hidden" name="total" value="<?php echo $this->horarioDefaults[6] ?>" />
                                <input type="hidden" name="total_extra" value="<?php echo $this->horarioDefaults[7] ?>" />
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-xs-2" for='horario1'>Entrada 1</label>
                        <div class="col-xs-2">
                            <span data-name="horario1" data-tabindex="1" data-default-time="<?php echo $this->horarioDefaults[0] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>

                        <label class="control-label col-xs-2" for='horario3'>Entrada 2</label>
                        <div class="col-xs-2">
                            <span data-name="horario3" data-tabindex="3" data-default-time="<?php echo $this->horarioDefaults[2] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>

                        <label class="control-label col-xs-2" for='horario5'>Entrada 3</label>
                        <div class="col-xs-2">
                            <span data-name="horario5" data-tabindex="5" data-default-time="<?php echo $this->horarioDefaults[4] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-xs-2" for='horario2'>Saída 1</label>
                        <div class="col-xs-2">
                            <span data-name="horario2" data-tabindex="2" data-default-time="<?php echo $this->horarioDefaults[1] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>

                        <label class="control-label col-xs-2" for='horario4'>Saída 2</label>
                        <div class="col-xs-2">
                            <span data-name="horario4" data-tabindex="4" data-default-time="<?php echo $this->horarioDefaults[3] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>

                        <label class="control-label col-xs-2" for='horario6'>Saída 3</label>
                        <div class="col-xs-2">
                            <span data-name="horario6" data-tabindex="6" data-default-time="<?php echo $this->horarioDefaults[5] ?>" data-component-timepicker class="col-xs-12"></span>
                        </div>
                    </div>

                    <div class='form-group'>
                        <label class="control-label col-xs-3">Total Hs.</label>
                        <div class="col-xs-3">
                            <p class='form-control-static'><strong class="lb-total-hs">08:00</strong></p>
                        </div>

                        <label class="control-label col-xs-3">Total Hs. Extras</label>
                        <div class="col-xs-3">
                            <p class='form-control-static'><strong class="lb-total-hs-extras">00:00</strong></p>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" data-confirmed="false" class="btn btn-primary btn-save">Redefinir horários</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="md-redefinir-datas" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form role="form" class="form-horizontal">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Redefinir datas de início e término da folha</h4>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label class="control-label col-xs-4">Mês: 4 / Ano: 2014</label>
                        <div class="col-xs-2">
                            <p class='form-control-static'>
                                <input type="hidden" name="cod" value="<?php echo $this->folha['cod'] ?>" />
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-xs-2" for='inicio'>Início</label>
                        <div class="col-xs-3">
                            <span data-name="inicio" data-picktime="false" data-tabindex="1" data-default-date="<?php echo $this->folha['inicio'] ?>" data-component-datetimepicker class="col-xs-12"></span>
                        </div>

                        <label class="control-label col-xs-2" for='termino'>Término</label>
                        <div class="col-xs-3">
                            <span data-name="termino" data-picktime="false" data-tabindex="3" data-default-date="<?php echo $this->folha['termino'] ?>" data-component-datetimepicker class="col-xs-12"></span>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" data-confirmed="false" class="btn btn-primary btn-save">Redefinir datas</button>
                </div>
            </form>
        </div>
    </div>
</div>