<div class="panel panel-default">
    <div class="panel-heading">
        Mês: <strong class="lb-mes"><?php echo $this->folha['mes'] ?></strong> / Ano: <strong class="lb-ano"><?php echo $this->folha['ano'] ?></strong>
        <div class="pull-right">
            <a href="<?php echo $this->basePath ?>main/index/ver-folha" id="btn-ver-mensal" type="button" title="Voltar para a folha de ponto" class="btn btn-xs btn-info"><?php echo $this->glyphicon('unshare', 'glyphicons') ?> Voltar para folha de ponto</a>
            <button id="btn-fechar-mes" type="button" title="Fechar mês" class="btn btn-xs btn-danger"><?php echo $this->glyphicon('lock', 'glyphicons') ?> Fechar mês</button>
        </div>
    </div>
    <?php echo $this->dg->datagrid() ?>
</div>