<div class="panel panel-default">
    <div class="panel-heading">Pesquisa de Usuários <a title="Novo Usuário" href="<?php echo $this->basePath ?>admin/user/new-item" class="btn btn-info btn-xs pull-right"><?php echo $this->glyphicon('plus-sign') ?> Novo Usuário</a></div>
    <div class="panel-body">
        <?php echo $this->form()->openTag('fm-user', ['method' => 'post', 'action' => $this->basePath . 'admin/user/list-items', 'class' => 'form-horizontal', 'role' => 'form']) ?>
        <fieldset>
            <?php echo $this->dg->getFormItems() ?>
            <?php echo $this->dg->getEntity()->getField('name')->getViewComponent()->setRequired(false)->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8') ?>
            <?php echo $this->dg->getEntity()->getField('email')->getViewComponent()->setRequired(false)->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8') ?>
            <?php echo $this->dg->getEntity()->getField('status')->getViewComponent()->setRequired(false)->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8') ?>
            <?php echo $this->form()->submitSearch()->formGroup('col-xs-12', '', 'col-xs-offset-3 col-xs-8') ?>
        </fieldset>
        <?php echo $this->form()->closeTag() ?>
    </div>
    <?php echo $this->dg ?>
</div>