<div class="panel panel-default">
    <div class="panel-heading">Pesquisa de Usuários <a title="Novo Usuário" href="<?php $this->basePath ?>/admin/user/new-item" class="btn btn-primary btn-xs pull-right"><?php echo $this->glyphicon('plus-sign') ?> Novo Usuário</a></div>
    <div class="panel-body">
        <?php echo $this->form->open() ?>
        <?php echo $this->dg->getInputHidden() ?>
        <fieldset>
            <?php echo $this->form->cod->render() ?>
            <div class="form-group">
                <?php echo $this->form->name->label('col-xs-3 text-right') ?>
                <div class="col-xs-8">
                    <?php echo $this->form->name->render() ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->form->email->label('col-xs-3 text-right') ?>
                <div class="col-xs-8">
                    <?php echo $this->form->email->render() ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->form->user_group->label('col-xs-3 text-right') ?>
                <div class="col-xs-8">
                    <?php echo $this->form->user_group->render() ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->form->status->label('col-xs-3 text-right') ?>
                <div class="col-xs-8">
                    <?php echo $this->form->status->render() ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-8 col-xs-offset-3">
                    <?php echo $this->form->submit->render() ?>
                </div>
            </div>
        </fieldset>
        <?php echo $this->form->close() ?>
    </div>
    <?php echo $this->dg->datagrid() ?>
</div>