<div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="panel panel-default">
        <div class="panel-heading">Usuários
            <a title="Ver Usuários" href="<?php echo $this->basePath ?>admin/user/list-items" class="btn btn-info btn-xs pull-right"><?php echo $this->glyphicon('search') ?> Ver Usuários</a>
            <?php if($this->edit): ?>
                <a title="Excluir Usuário" data-confirmation data-placement="bottom" href="<?php echo $this->basePath ?>admin/user/delete-item/cod/<?php echo $this->edit ?>" class="btn btn-danger btn-xs pull-right margin-right-xs"><?php echo $this->glyphicon('remove-sign') ?> Excluir Usuário</a>
            <?php endif; ?>
        </div>
        <div class="panel-body">
            <?php echo $this->form()->openTag('fm-user', ['method' => 'post', 'action' => $this->basePath . 'admin/user/new-item', 'class' => 'form-horizontal', 'role' => 'form']) ?>
            <fieldset>
                <?php echo $this->entity->getField('cod')->getViewComponent()->render() ?>
                <?php echo $this->entity->getField('name')->getViewComponent()->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8') ?>
                <?php echo $this->entity->getField('email')->getViewComponent()->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8') ?>
                <?php echo $this->entity->getField('password')->getViewComponent()->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8') ?>
                <?php echo \KF\Lib\View\Html\InputPassword::create('re-password', 'Repita a senha')->setPlaceholder('Repita a senha')->setRequired(true)->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8') ?>
                <?php echo $this->entity->getField('user_group')->getViewComponent()->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8') ?>
                <?php echo $this->entity->getField('status')->getViewComponent()->formGroup('col-xs-12', 'col-xs-3 text-right', 'col-xs-8') ?>
                <?php echo $this->form()->submitSave()->formGroup('col-xs-12', '', 'col-xs-offset-3 col-xs-8') ?>
            </fieldset>
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>