<div class="col-sm-2 col-xs-12">
    <ul class="nav nav-pills nav-stacked well">
        <li  class="active"><a href="#"><i class="fa fa-envelope"></i> Compose</a></li>
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
        <li><a href="#"><i class="fa fa-key"></i> Security</a></li>
        <li><a href="#"><i class="fa fa-sign-out"></i> Logout</a></li>
    </ul>
</div>
<div class="col-sm-10 col-xs-12">
    <div class="panel">
        <img class="pic img-circle" src="<?php echo $this->usuario['photo'] ?>" alt="..." />
        <div class="name"><small><?php echo $this->usuario['name'] ?></small></div>
        <a id="btn-change-cover" href="#" class="btn btn-xs btn-primary pull-right" style="margin:10px;"><span class="glyphicon glyphicon-picture"></span> Mudar imagem</a>
    </div>

    <br /><br /><br />
    <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a href="#inbox" data-toggle="tab"><i class="fa fa-envelope-o"></i> Inbox</a></li>
        <li><a href="#sent" data-toggle="tab"><i class="fa fa-reply-all"></i> Sent</a></li>
        <li><a href="#assignment" data-toggle="tab"><i class="fa fa-file-text-o"></i> Assignment</a></li>
        <li><a href="#event" data-toggle="tab"><i class="fa fa-clock-o"></i> Event</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="inbox">
            <br />
            <a type="button" data-toggle="collapse" data-target=".opa">
                <div class="btn-toolbar well well-sm" role="toolbar"  style="margin:0px;">
                    <div class="btn-group"><input type="checkbox"></div>
                    <div class="btn-group col-md-3">Admin Kumar</div>
                    <div class="btn-group col-md-8"><b>Hi Check this new Bootstrap plugin</b> <div class="pull-right"><i class="glyphicon glyphicon-time"></i> 12:10 PM <button class="btn btn-primary btn-xs" data-toggle="modal" data-target=".bs-example-modal-lg"><i class="fa fa-share-square-o"> Reply</i></button></div> </div>
                </div>
            </a>
            <div id="a1" class="collapse out well opa">This is the message body1</div>
            <br>
            <button class="btn btn-primary btn-xs collapse out opa"><i class="fa fa-check-square-o"></i> Delete Checked Item's</button>
        </div>
        <div class="tab-pane" id="sent">
            <br />
            <a type="button" data-toggle="collapse" data-target="#s1">
                <div class="btn-toolbar well well-sm" role="toolbar"  style="margin:0px;">
                    <div class="btn-group"><input type="checkbox"></div>
                    <div class="btn-group col-md-3">Kumar</div>
                    <div class="btn-group col-md-8"><b>This is reply from Bootstrap plugin</b> <div class="pull-right"><i class="glyphicon glyphicon-time"></i> 12:30 AM</div> </div>
                </div>
            </a>
            <div id="s1" class="collapse out well">This is the message body1</div>
            <br>
            <button class="btn btn-primary btn-xs"><i class="fa fa-check-square-o"></i> Delete Checked Item's</button>
        </div>
        <div class="tab-pane" id="assignment">
            <br />
            <a href=""><div class="well well-sm" style="margin:0px;">Open GL Assignments <span class="pull-right"><i class="glyphicon glyphicon-time"></i> 12:20 AM 20 Dec 2014 </span></div></a>        
        </div>
        <div class="tab-pane" id="event">
            <div class="media">
                <br />
                <a class="pull-left" href="#">
                    <img class="media-object img-thumbnail" width="100" src="http://cfi-sinergia.epfl.ch/files/content/sites/cfi-sinergia/files/WORKSHOPS/Workshop1.jpg" alt="...">
                </a>
                <div class="media-body">
                    <h4 class="media-heading">Animation Workshop</h4>
                    2Days animation workshop to be conducted
                </div>
            </div>
        </div>
    </div>
</div>