<div class="row">
    <h2>Painel Administrativo</h2>
    <hr />
    <div class="col-sm-6">
        <div class="blockquote-box blockquote-warning clearfix">
            <div class="square pull-left">
                <span class="glyphicon glyphicon-tags glyphicon-lg"></span>
            </div>
            <h4>Usuários</h4>
            <p>
            <ul class="list-unstyled list-inline">
                <li><?php echo $this->glyphicon('plus-sign') ?> <a href="<?php echo $this->basePath ?>admin/user-group/new-item">Novo Grupo de Usuário</a></li>
                <li><?php echo $this->glyphicon('plus-sign') ?> <a href="<?php echo $this->basePath ?>admin/user/new-item">Novo Usuário</a></li>
                <li><?php echo $this->glyphicon('list-alt') ?> <a href="<?php echo $this->basePath ?>admin/user-group/list-items">Ver Grupos de Usuários</a></li>
                <li><?php echo $this->glyphicon('list-alt') ?> <a href="<?php echo $this->basePath ?>admin/user/list-items">Ver Usuários</a></li>
            </ul>
            </p>
        </div>
    </div>
</div>