<div class="panel panel-default">
    <div class="panel-heading">Menus <a title="Novo Menu" href="<?php echo $this->basePath ?>admin/menu/new-item" class="btn btn-primary btn-xs pull-right"><?php echo $this->glyphicon('plus-sign') ?> Novo Menu</a></div>
    <div class="panel-body">
        <?php echo $this->form->open() ?>
        <?php echo $this->dg->getInputHidden() ?>
        <fieldset>
            <?php echo $this->form->cod->render() ?>
            <div class="form-group">
                <?php echo $this->form->name->label('col-xs-3 text-right') ?>
                <div class="col-xs-8">
                    <?php echo $this->form->name->render() ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->form->codename->label('col-xs-3 text-right') ?>
                <div class="col-xs-8">
                    <?php echo $this->form->codename->render() ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-8 col-xs-offset-3">
                    <?php echo $this->form->submit->render() ?>
                </div>
            </div>
        </fieldset>
        <?php echo $this->form->close() ?>
    </div>
    <?php echo $this->dg->datagrid() ?>
</div>
