<div class="col-xs-12">
    <div class="panel panel-default">
        <div class="panel-heading">Menu <a title="Ver Menus" href="<?php $this->basePath ?>/admin/menu/list-items" class="btn btn-primary btn-xs pull-right"><?php echo $this->glyphicon('search') ?> Ver Menus</a></div>
        <div class="panel-body">
            <?php echo $this->form->open() ?>
            <fieldset>
                <?php echo $this->form->cod->render() ?>
                <div class="form-group">
                    <?php echo $this->form->name->label('col-xs-3 text-right') ?>
                    <div class="col-xs-8">
                        <?php echo $this->form->name->render() ?>
                    </div>
                </div>
                <div class="col-xs-12">

                    <div id="block-menu-tree" class="col-sm-6 col-xs-12 well well-sm">
                        <div id="menu-tree">
                            <ul>
                                <li id="phtml_1">
                                    <a href="#">Root node 1</a>
                                </li>
                            </ul>
                        </div>

                        <div id="block-menu-tree-aux" class="row col-xs-12">
                            <a href="#" class="btn btn-warning"><?php echo $this->glyphicon('italic') ?> Renomear</a>
                            <a href="#" class="btn btn-danger"><?php echo $this->glyphicon('remove') ?> Excluir</a>
                            <a href="#" class="btn btn-primary"><?php echo $this->glyphicon('plus') ?> Novo Filho</a>
                            <a href="#" class="btn btn-primary"><?php echo $this->glyphicon('plus') ?> Novo Irmão</a>
                        </div>


                        <!--ul>
                            <li id="phtml_1">
                                <a href="#">Root node 1</a>
                                <ul>
                                    <li id="phtml_2">
                                        <a href="#">Child node 1</a>
                                    </li>
                                    <li id="phtml_3">
                                        <a href="#">Child node 2</a>
                                    </li>
                                    <li id="phtml_4">
                                        <a href="#">Child node 3</a>
                                    </li>
                                </ul>
                            </li>
                            <li id="phtml_5">
                                <a href="#">Root node 2</a>
                            </li>
                            <li id="phtml_6">
                                <a href="#">Root node 2</a>
                            </li>
                            <li id="phtml_7">
                                <a href="#">Root node 2</a>
                            </li>
                        </ul-->
                    </div>

                    <div id="block-form-info" class="col-sm-6 col-xs-12 well well-sm">
                        <br /><br />
                        <div class="text-center">
                            <div class="btn btn-default disabled text-center text-muted">Selecione um item</div>
                        </div>
                    </div>

                    <!--ul class="list-group well">
                        <li data-layer="1" class="list-group-item">
                            <label class="">Root</label>
                            <div class="btn-group pull-right">
                                <button title="Adicionar um filho" class="btn-add-item btn btn-success btn-xs"><?php echo $this->glyphicon('plus') ?></button>
                            </div>
                        </li>
                    </ul-->
                </div>
                <div class="form-group">
                    <div class="col-xs-12 text-center">
                        <?php echo $this->form->submit->render() ?>
                    </div>
                </div>
            </fieldset>
            <?php echo $this->form->close() ?>
        </div>
    </div>
</div>

<div class="snippets hidden">
    <li data-layer="1" class="list-group-item">
        <label></label>
        <div class="btn-group pull-right">
            <button title="Propriedades" class="btn-edit-item btn btn-info btn-xs"><?php echo $this->glyphicon('info-sign') ?></button>
            <button title="Remover" class="btn-del-item btn btn-warning btn-xs"><?php echo $this->glyphicon('trash') ?></button>
            <button title="Adicionar um filho" class="btn-add-item btn btn-success btn-xs"><?php echo $this->glyphicon('plus') ?></button>
        </div>
    </li>
</div>

<div class="modal fade" id="md-del" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Remover item?</h4>
            </div>
            <div class="modal-body">
                Deseja mesmo remover este item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary"><?php echo $this->glyphicon('trash') ?> &nbsp;Remover</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="md-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Propriedades</h4>
            </div>
            <div class="modal-body">
                <form role="form" class="form-horizontal">
                    <fieldset>
                        <div class="form-group">
                            <label class="control-label col-xs-3 text-right" for="name">Nome</label>
                            <div class="col-xs-8">
                                <input class="form-control" type="text" name="name" placeholder="Nome" title="Nome" />
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary"><?php echo $this->glyphicon('ok') ?> &nbsp;Salvar</button>
            </div>
        </div>
    </div>
</div>