<form class="form-signin" role="form" action="<?php echo $this->basePath ?>admin/auth/login" method="post">
    <h2 class="form-signin-heading">Faça o login</h2>
    <hr />
    <input type="email" name="email" class="form-control" placeholder="E-mail" required autofocus>
    <input type="password" name="senha" class="form-control" placeholder="Senha" required>
    <button class="btn btn-lg btn-success btn-block" type="submit">Login</button>
</form>