<form class="form-signin well" role="form" action="<?php echo $this->basePath ?>admin/auth/login" method="post">
    <div class="text-center"><img src='<?php echo $this->themePath ?>img/logo.png' /></div>
    <h2 class="text-center form-signin-heading">Faça o login</h2>
    <hr />
    <input type="email" name="email" class="form-control" placeholder="E-mail" required autofocus>
    <input type="password" name="password" class="form-control" placeholder="Senha" required>
    <button class="btn btn-lg btn-success btn-block" type="submit">Login</button>
</form>